name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run code test
        run: echo "testing..."
      - run: echo "testing 2 ..."
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "building"